// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

public partial class ColegiosCOLContext : DbContext
{
    public ColegiosCOLContext(DbContextOptions<ColegiosCOLContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tb_actividades_extracurriculares> tb_actividades_extracurriculares { get; set; }

    public virtual DbSet<tb_acudientes> tb_acudientes { get; set; }

    public virtual DbSet<tb_anos_escolares> tb_anos_escolares { get; set; }

    public virtual DbSet<tb_areas> tb_areas { get; set; }

    public virtual DbSet<tb_asignacion_cursos> tb_asignacion_cursos { get; set; }

    public virtual DbSet<tb_auditorias> tb_auditorias { get; set; }

    public virtual DbSet<tb_aulas> tb_aulas { get; set; }

    public virtual DbSet<tb_boletas> tb_boletas { get; set; }

    public virtual DbSet<tb_calificaciones> tb_calificaciones { get; set; }

    public virtual DbSet<tb_carnets> tb_carnets { get; set; }

    public virtual DbSet<tb_certificados> tb_certificados { get; set; }

    public virtual DbSet<tb_ciudades> tb_ciudades { get; set; }

    public virtual DbSet<tb_colegios> tb_colegios { get; set; }

    public virtual DbSet<tb_colegios_perfiles> tb_colegios_perfiles { get; set; }

    public virtual DbSet<tb_comunicaciones> tb_comunicaciones { get; set; }

    public virtual DbSet<tb_comunicaciones_institucionales> tb_comunicaciones_institucionales { get; set; }

    public virtual DbSet<tb_configuracion_mensajeria> tb_configuracion_mensajeria { get; set; }

    public virtual DbSet<tb_consulta_asistencia> tb_consulta_asistencia { get; set; }

    public virtual DbSet<tb_consulta_notas> tb_consulta_notas { get; set; }

    public virtual DbSet<tb_consulta_pagos> tb_consulta_pagos { get; set; }

    public virtual DbSet<tb_contratos> tb_contratos { get; set; }

    public virtual DbSet<tb_control_acceso> tb_control_acceso { get; set; }

    public virtual DbSet<tb_departamentos> tb_departamentos { get; set; }

    public virtual DbSet<tb_empleados> tb_empleados { get; set; }

    public virtual DbSet<tb_encuestas_satisfaccion> tb_encuestas_satisfaccion { get; set; }

    public virtual DbSet<tb_estudiantes> tb_estudiantes { get; set; }

    public virtual DbSet<tb_evaluaciones> tb_evaluaciones { get; set; }

    public virtual DbSet<tb_facturas> tb_facturas { get; set; }

    public virtual DbSet<tb_grados> tb_grados { get; set; }

    public virtual DbSet<tb_historial_academico> tb_historial_academico { get; set; }

    public virtual DbSet<tb_incidencias> tb_incidencias { get; set; }

    public virtual DbSet<tb_informes_auditoria> tb_informes_auditoria { get; set; }

    public virtual DbSet<tb_inscripciones> tb_inscripciones { get; set; }

    public virtual DbSet<tb_logs> tb_logs { get; set; }

    public virtual DbSet<tb_mantenimiento> tb_mantenimiento { get; set; }

    public virtual DbSet<tb_modulos> tb_modulos { get; set; }

    public virtual DbSet<tb_nominas> tb_nominas { get; set; }

    public virtual DbSet<tb_noticias> tb_noticias { get; set; }

    public virtual DbSet<tb_pagina_institucional> tb_pagina_institucional { get; set; }

    public virtual DbSet<tb_paginas> tb_paginas { get; set; }

    public virtual DbSet<tb_pagos> tb_pagos { get; set; }

    public virtual DbSet<tb_paises> tb_paises { get; set; }

    public virtual DbSet<tb_parametros> tb_parametros { get; set; }

    public virtual DbSet<tb_participacion_actividades> tb_participacion_actividades { get; set; }

    public virtual DbSet<tb_perfiles> tb_perfiles { get; set; }

    public virtual DbSet<tb_permisos> tb_permisos { get; set; }

    public virtual DbSet<tb_planes_accion> tb_planes_accion { get; set; }

    public virtual DbSet<tb_planes_estudio> tb_planes_estudio { get; set; }

    public virtual DbSet<tb_preguntas_encuesta> tb_preguntas_encuesta { get; set; }

    public virtual DbSet<tb_prioridad_paginas> tb_prioridad_paginas { get; set; }

    public virtual DbSet<tb_recursos_educativos> tb_recursos_educativos { get; set; }

    public virtual DbSet<tb_reportes> tb_reportes { get; set; }

    public virtual DbSet<tb_reportes_asistencia> tb_reportes_asistencia { get; set; }

    public virtual DbSet<tb_reportes_financieros> tb_reportes_financieros { get; set; }

    public virtual DbSet<tb_respuestas_encuesta> tb_respuestas_encuesta { get; set; }

    public virtual DbSet<tb_rutas_documentos> tb_rutas_documentos { get; set; }

    public virtual DbSet<tb_tipos_documentos> tb_tipos_documentos { get; set; }

    public virtual DbSet<tb_tipos_identificacion> tb_tipos_identificacion { get; set; }

    public virtual DbSet<tb_tipos_parentesco> tb_tipos_parentesco { get; set; }

    public virtual DbSet<tb_transiciones_estudiantes> tb_transiciones_estudiantes { get; set; }

    public virtual DbSet<tb_usuarios> tb_usuarios { get; set; }

    public virtual DbSet<tb_usuarios_logueados> tb_usuarios_logueados { get; set; }

    public virtual DbSet<tb_usuarios_perfiles> tb_usuarios_perfiles { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tb_actividades_extracurriculares>(entity =>
        {
            entity.HasKey(e => e.id_actividad).HasName("PK__tb_activ__DCD34883195DF44A");
        });

        modelBuilder.Entity<tb_acudientes>(entity =>
        {
            entity.HasKey(e => e.id_acudiente).HasName("PK__tb_acudi__8F89A4F51281E021");
        });

        modelBuilder.Entity<tb_anos_escolares>(entity =>
        {
            entity.HasKey(e => e.id_ano_escolar).HasName("PK__tb_anos___98824276348E6BDE");
        });

        modelBuilder.Entity<tb_areas>(entity =>
        {
            entity.HasKey(e => e.id_area).HasName("PK__tb_areas__8A8C837BD4390C79");
        });

        modelBuilder.Entity<tb_asignacion_cursos>(entity =>
        {
            entity.HasKey(e => e.id_asignacion).HasName("PK__tb_asign__C3F7F966CBA911BF");

            entity.HasOne(d => d.fk_id_docenteNavigation).WithMany(p => p.tb_asignacion_cursos).HasConstraintName("FK_Asignacion_Docente");
        });

        modelBuilder.Entity<tb_auditorias>(entity =>
        {
            entity.HasKey(e => e.id_auditoria).HasName("PK__tb_audit__9644A3CE2D71A60D");
        });

        modelBuilder.Entity<tb_aulas>(entity =>
        {
            entity.HasKey(e => e.id_aula).HasName("PK__tb_aulas__B19134FE75021637");
        });

        modelBuilder.Entity<tb_boletas>(entity =>
        {
            entity.HasKey(e => e.id_boleta).HasName("PK__tb_bolet__AD5482CDCBB7B205");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_boletas).HasConstraintName("FK_Boleta_Estudiante");
        });

        modelBuilder.Entity<tb_calificaciones>(entity =>
        {
            entity.HasKey(e => e.id_calificacion).HasName("PK__tb_calif__38CEF35C89809228");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_calificaciones).HasConstraintName("FK_Calificacion_Estudiante");

            entity.HasOne(d => d.fk_id_evaluacionNavigation).WithMany(p => p.tb_calificaciones).HasConstraintName("FK_Calificacion_Evaluacion");
        });

        modelBuilder.Entity<tb_carnets>(entity =>
        {
            entity.HasKey(e => e.id_carnet).HasName("PK__tb_carne__1688C1928E44A370");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_carnets).HasConstraintName("FK_Carnet_Estudiante");
        });

        modelBuilder.Entity<tb_certificados>(entity =>
        {
            entity.HasKey(e => e.id_certificado).HasName("PK__tb_certi__B7A2D13BE3DA967F");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_certificados).HasConstraintName("FK_Certificado_Estudiante");
        });

        modelBuilder.Entity<tb_ciudades>(entity =>
        {
            entity.HasKey(e => e.id_ciudad).HasName("PK__tb_ciuda__B7DC4CD5CEFB1AAA");

            entity.HasOne(d => d.fk_id_departamentoNavigation).WithMany(p => p.tb_ciudades).HasConstraintName("FK_Ciudad_Departamento");
        });

        modelBuilder.Entity<tb_colegios>(entity =>
        {
            entity.HasKey(e => e.id_colegio).HasName("PK__tb_coleg__34F63C1D7A83EBD4");
        });

        modelBuilder.Entity<tb_colegios_perfiles>(entity =>
        {
            entity.HasOne(d => d.fk_id_colegioNavigation).WithMany(p => p.tb_colegios_perfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_colegios_perfiles_tb_oficinas");

            entity.HasOne(d => d.fk_id_perfilNavigation).WithMany(p => p.tb_colegios_perfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_oficinas_perfiles_tb_perfiles");
        });

        modelBuilder.Entity<tb_comunicaciones>(entity =>
        {
            entity.HasKey(e => e.id_comunicacion).HasName("PK__tb_comun__D76C50711903B69D");

            entity.HasOne(d => d.fk_id_usuarioNavigation).WithMany(p => p.tb_comunicaciones).HasConstraintName("FK_Comunicacion_Usuario");
        });

        modelBuilder.Entity<tb_comunicaciones_institucionales>(entity =>
        {
            entity.HasKey(e => e.id_comunicacion).HasName("PK__tb_comun__D76C5071A13C8D30");

            entity.HasOne(d => d.fk_id_colegioNavigation).WithMany(p => p.tb_comunicaciones_institucionales).HasConstraintName("FK_Comunicaciones_Colegio");
        });

        modelBuilder.Entity<tb_configuracion_mensajeria>(entity =>
        {
            entity.HasKey(e => e.id_configuracion).HasName("PK__tb_confi__16A13EBD0336995A");
        });

        modelBuilder.Entity<tb_consulta_asistencia>(entity =>
        {
            entity.HasKey(e => e.id_consulta).HasName("PK__tb_consu__6F53588B4B8CF108");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_consulta_asistencia).HasConstraintName("FK_Consulta_Asistencia_Estudiante");
        });

        modelBuilder.Entity<tb_consulta_notas>(entity =>
        {
            entity.HasKey(e => e.id_consulta).HasName("PK__tb_consu__6F53588B3A9DF420");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_consulta_notas).HasConstraintName("FK_Consulta_Notas_Estudiante");
        });

        modelBuilder.Entity<tb_consulta_pagos>(entity =>
        {
            entity.HasKey(e => e.id_consulta).HasName("PK__tb_consu__6F53588B702BDF04");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_consulta_pagos).HasConstraintName("FK_Consulta_Pagos_Estudiante");
        });

        modelBuilder.Entity<tb_contratos>(entity =>
        {
            entity.HasKey(e => e.id_contrato).HasName("PK__tb_contr__FF5F2A56715F9E2A");

            entity.HasOne(d => d.fk_id_empleadoNavigation).WithMany(p => p.tb_contratos).HasConstraintName("FK_Contrato_Empleado");
        });

        modelBuilder.Entity<tb_control_acceso>(entity =>
        {
            entity.HasKey(e => e.id_control).HasName("PK__tb_contr__3AAC4A77BA934DFF");

            entity.HasOne(d => d.fk_id_carnetNavigation).WithMany(p => p.tb_control_acceso).HasConstraintName("FK_Control_Acceso_Carnet");
        });

        modelBuilder.Entity<tb_departamentos>(entity =>
        {
            entity.HasKey(e => e.id_departamento).HasName("PK__tb_depar__64F37A1686AE227C");

            entity.HasOne(d => d.fk_id_paisNavigation).WithMany(p => p.tb_departamentos).HasConstraintName("FK_Departamento_Pais");
        });

        modelBuilder.Entity<tb_empleados>(entity =>
        {
            entity.HasKey(e => e.id_empleado).HasName("PK__tb_emple__88B5139418E9F4F6");
        });

        modelBuilder.Entity<tb_encuestas_satisfaccion>(entity =>
        {
            entity.HasKey(e => e.id_encuesta).HasName("PK__tb_encue__013535C309AEBEF3");
        });

        modelBuilder.Entity<tb_estudiantes>(entity =>
        {
            entity.HasKey(e => e.id_estudiante).HasName("PK__tb_estud__E0B2763C77250665");

            entity.HasOne(d => d.fk_id_gradoNavigation).WithMany(p => p.tb_estudiantes).HasConstraintName("FK_Estudiante_Grado");
        });

        modelBuilder.Entity<tb_evaluaciones>(entity =>
        {
            entity.HasKey(e => e.id_evaluacion).HasName("PK__tb_evalu__65DE60C555B14AF3");

            entity.HasOne(d => d.fk_id_cursoNavigation).WithMany(p => p.tb_evaluaciones).HasConstraintName("FK_Evaluacion_Curso");
        });

        modelBuilder.Entity<tb_facturas>(entity =>
        {
            entity.HasKey(e => e.id_factura).HasName("PK__tb_factu__6C08ED538C596D2A");

            entity.HasOne(d => d.fk_id_pagoNavigation).WithMany(p => p.tb_facturas).HasConstraintName("FK_Factura_Pago");
        });

        modelBuilder.Entity<tb_grados>(entity =>
        {
            entity.HasKey(e => e.id_grado).HasName("PK__tb_grado__6DB797EE57234046");
        });

        modelBuilder.Entity<tb_historial_academico>(entity =>
        {
            entity.HasKey(e => e.id_historial).HasName("PK__tb_histo__76E6C50265BCBD08");

            entity.HasOne(d => d.fk_id_ano_escolarNavigation).WithMany(p => p.tb_historial_academico).HasConstraintName("FK_Historial_Academico_Ano_Escolar");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_historial_academico).HasConstraintName("FK_Historial_Academico_Estudiante");

            entity.HasOne(d => d.fk_id_gradoNavigation).WithMany(p => p.tb_historial_academico).HasConstraintName("FK_Historial_Academico_Grado");
        });

        modelBuilder.Entity<tb_incidencias>(entity =>
        {
            entity.HasKey(e => e.id_incidencia).HasName("PK__tb_incid__D7757E7697309B9A");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_incidencias).HasConstraintName("FK_Incidencia_Estudiante");
        });

        modelBuilder.Entity<tb_informes_auditoria>(entity =>
        {
            entity.HasKey(e => e.id_informe).HasName("PK__tb_infor__ECCCE10F756998F7");

            entity.HasOne(d => d.fk_id_auditoriaNavigation).WithMany(p => p.tb_informes_auditoria).HasConstraintName("FK_Informe_Auditoria");
        });

        modelBuilder.Entity<tb_inscripciones>(entity =>
        {
            entity.HasKey(e => e.id_inscripcion).HasName("PK__tb_inscr__CB0117BA8F2350B2");

            entity.HasOne(d => d.fk_id_colegioNavigation).WithMany(p => p.tb_inscripciones).HasConstraintName("FK_Inscripcion_Colegio");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_inscripciones).HasConstraintName("FK_Inscripcion_Estudiante");

            entity.HasOne(d => d.fk_id_gradoNavigation).WithMany(p => p.tb_inscripciones).HasConstraintName("FK_Inscripcion_Grado");
        });

        modelBuilder.Entity<tb_logs>(entity =>
        {
            entity.HasKey(e => e.id_log).HasName("PK__tb_logs__6CC851FE36C4D521");
        });

        modelBuilder.Entity<tb_mantenimiento>(entity =>
        {
            entity.HasKey(e => e.id_mantenimiento).HasName("PK__tb_mante__707E5D167BF32199");

            entity.HasOne(d => d.fk_id_aulaNavigation).WithMany(p => p.tb_mantenimiento).HasConstraintName("FK_Mantenimiento_Aula");
        });

        modelBuilder.Entity<tb_modulos>(entity =>
        {
            entity.HasKey(e => e.id_modulo).HasName("PK_tb_modulos_1");
        });

        modelBuilder.Entity<tb_nominas>(entity =>
        {
            entity.HasKey(e => e.id_nomina).HasName("PK__tb_nomin__1E7025F6E6F56D57");

            entity.HasOne(d => d.fk_id_empleadoNavigation).WithMany(p => p.tb_nominas).HasConstraintName("FK_Nomina_Empleado");
        });

        modelBuilder.Entity<tb_noticias>(entity =>
        {
            entity.HasKey(e => e.id_noticia).HasName("PK__tb_notic__1D4A6BA143217743");
        });

        modelBuilder.Entity<tb_pagina_institucional>(entity =>
        {
            entity.HasKey(e => e.id_pagina).HasName("PK__tb_pagin__A2A7C7B6FF32B551");
        });

        modelBuilder.Entity<tb_paginas>(entity =>
        {
            entity.HasOne(d => d.fk_id_moduloNavigation).WithMany(p => p.tb_paginas)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_paginas_tb_modulos");
        });

        modelBuilder.Entity<tb_pagos>(entity =>
        {
            entity.HasKey(e => e.id_pago).HasName("PK__tb_pagos__0941B074AA2B6CAE");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_pagos).HasConstraintName("FK_Pago_Estudiante");
        });

        modelBuilder.Entity<tb_paises>(entity =>
        {
            entity.HasKey(e => e.id_pais).HasName("PK__tb_paise__0941A3A72875E7BE");
        });

        modelBuilder.Entity<tb_parametros>(entity =>
        {
            entity.HasKey(e => e.id_parametro).HasName("PK__tb_param__3D24E32554F5D1AE");
        });

        modelBuilder.Entity<tb_participacion_actividades>(entity =>
        {
            entity.HasKey(e => e.id_participacion).HasName("PK__tb_parti__E42D0FE09ED950E3");

            entity.HasOne(d => d.fk_id_actividadNavigation).WithMany(p => p.tb_participacion_actividades).HasConstraintName("FK_Participacion_Actividad");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_participacion_actividades).HasConstraintName("FK_Participacion_Estudiante");
        });

        modelBuilder.Entity<tb_permisos>(entity =>
        {
            entity.HasOne(d => d.fk_id_paginaNavigation).WithMany(p => p.tb_permisos).HasConstraintName("FK_tb_permisos_tb_paginas");

            entity.HasOne(d => d.fk_id_perfilNavigation).WithMany(p => p.tb_permisos)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_permisos_tb_perfiles");
        });

        modelBuilder.Entity<tb_planes_accion>(entity =>
        {
            entity.HasKey(e => e.id_plan_accion).HasName("PK__tb_plane__4867AC2637DC53E2");

            entity.HasOne(d => d.fk_id_incidenciaNavigation).WithMany(p => p.tb_planes_accion).HasConstraintName("FK_Plan_Accion_Incidencia");
        });

        modelBuilder.Entity<tb_planes_estudio>(entity =>
        {
            entity.HasKey(e => e.id_plan_estudio).HasName("PK__tb_plane__C3839BA54A9CBDE2");
        });

        modelBuilder.Entity<tb_preguntas_encuesta>(entity =>
        {
            entity.HasKey(e => e.id_pregunta).HasName("PK__tb_pregu__6867FFA4A610B559");

            entity.HasOne(d => d.fk_id_encuestaNavigation).WithMany(p => p.tb_preguntas_encuesta).HasConstraintName("FK_Pregunta_Encuesta");
        });

        modelBuilder.Entity<tb_prioridad_paginas>(entity =>
        {
            entity.HasKey(e => e.id_prioridad).HasName("PK__tb_prior__EF3DAB4016D1D826");

            entity.HasOne(d => d.fk_id_paginaNavigation).WithMany(p => p.tb_prioridad_paginas).HasConstraintName("FK_Prioridad_Pagina");
        });

        modelBuilder.Entity<tb_recursos_educativos>(entity =>
        {
            entity.HasKey(e => e.id_recurso).HasName("PK__tb_recur__2B386DE4CD85764F");
        });

        modelBuilder.Entity<tb_reportes>(entity =>
        {
            entity.HasKey(e => e.id_reporte).HasName("PK__tb_repor__87E4F5CB057097F0");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_reportes).HasConstraintName("FK_Reporte_Estudiante");
        });

        modelBuilder.Entity<tb_reportes_asistencia>(entity =>
        {
            entity.HasKey(e => e.id_reporte_asistencia).HasName("PK__tb_repor__20571E09906EF354");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_reportes_asistencia).HasConstraintName("FK_Reporte_Asistencia_Estudiante");
        });

        modelBuilder.Entity<tb_reportes_financieros>(entity =>
        {
            entity.HasKey(e => e.id_reporte).HasName("PK__tb_repor__87E4F5CBBFA06C18");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_reportes_financieros).HasConstraintName("FK_Reporte_Financiero_Estudiante");
        });

        modelBuilder.Entity<tb_respuestas_encuesta>(entity =>
        {
            entity.HasKey(e => e.id_respuesta).HasName("PK__tb_respu__14E55589A966E103");

            entity.HasOne(d => d.fk_id_preguntaNavigation).WithMany(p => p.tb_respuestas_encuesta).HasConstraintName("FK_Respuesta_Pregunta");
        });

        modelBuilder.Entity<tb_rutas_documentos>(entity =>
        {
            entity.HasKey(e => e.id_ruta).HasName("PK__tb_rutas__33C9344FFBBE83E0");
        });

        modelBuilder.Entity<tb_tipos_documentos>(entity =>
        {
            entity.HasKey(e => e.id_tipo_documento).HasName("PK__tb_tipos__9F38507C1067E8B4");
        });

        modelBuilder.Entity<tb_tipos_identificacion>(entity =>
        {
            entity.HasKey(e => e.id_tipo_identificacion).HasName("PK__tb_tipos__65DACF6C3E731376");
        });

        modelBuilder.Entity<tb_tipos_parentesco>(entity =>
        {
            entity.HasKey(e => e.id_parentesco).HasName("PK__tb_tipos__8F56AC31DC34E979");
        });

        modelBuilder.Entity<tb_transiciones_estudiantes>(entity =>
        {
            entity.HasKey(e => e.id_transicion).HasName("PK__tb_trans__C5A33F4F0B94442A");

            entity.HasOne(d => d.fk_id_ano_escolarNavigation).WithMany(p => p.tb_transiciones_estudiantes).HasConstraintName("FK_Transicion_Ano_Escolar");

            entity.HasOne(d => d.fk_id_estudianteNavigation).WithMany(p => p.tb_transiciones_estudiantes).HasConstraintName("FK_Transicion_Estudiante");

            entity.HasOne(d => d.fk_id_grado_actualNavigation).WithMany(p => p.tb_transiciones_estudiantesfk_id_grado_actualNavigation).HasConstraintName("FK_Transicion_Grado_Actual");

            entity.HasOne(d => d.fk_id_grado_siguienteNavigation).WithMany(p => p.tb_transiciones_estudiantesfk_id_grado_siguienteNavigation).HasConstraintName("FK_Transicion_Grado_Siguiente");
        });

        modelBuilder.Entity<tb_usuarios_perfiles>(entity =>
        {
            entity.HasOne(d => d.fk_id_perfilNavigation).WithMany(p => p.tb_usuarios_perfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_usuarios_perfiles_tb_perfiles");

            entity.HasOne(d => d.fk_id_usuarioNavigation).WithMany(p => p.tb_usuarios_perfiles)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_tb_usuarios_perfiles_tb_usuarios");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}