// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_aulas", Schema = "mcol")]
public partial class tb_aulas
{
    [Key]
    public int id_aula { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }

    public int? capacidad { get; set; }

    [InverseProperty("fk_id_aulaNavigation")]
    public virtual ICollection<tb_mantenimiento> tb_mantenimiento { get; set; } = new List<tb_mantenimiento>();
}