// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_asignacion_cursos", Schema = "mcol")]
public partial class tb_asignacion_cursos
{
    [Key]
    public int id_asignacion { get; set; }

    public int? fk_id_docente { get; set; }

    public int? fk_id_curso { get; set; }

    [ForeignKey("fk_id_docente")]
    [InverseProperty("tb_asignacion_cursos")]
    public virtual tb_empleados fk_id_docenteNavigation { get; set; }

    [InverseProperty("fk_id_cursoNavigation")]
    public virtual ICollection<tb_evaluaciones> tb_evaluaciones { get; set; } = new List<tb_evaluaciones>();
}