// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_acudientes", Schema = "mcol")]
public partial class tb_acudientes
{
    [Key]
    public int id_acudiente { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }

    [StringLength(50)]
    public string apellido { get; set; }

    [StringLength(20)]
    public string telefono { get; set; }
}