// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_areas", Schema = "mcol")]
public partial class tb_areas
{
    [Key]
    public int id_area { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }
}