// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_actividades_extracurriculares", Schema = "mcol")]
public partial class tb_actividades_extracurriculares
{
    [Key]
    public int id_actividad { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [InverseProperty("fk_id_actividadNavigation")]
    public virtual ICollection<tb_participacion_actividades> tb_participacion_actividades { get; set; } = new List<tb_participacion_actividades>();
}