// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_anos_escolares", Schema = "mcol")]
public partial class tb_anos_escolares
{
    [Key]
    public int id_ano_escolar { get; set; }

    public int? ano_inicio { get; set; }

    public int? ano_fin { get; set; }

    [StringLength(50)]
    public string descripcion { get; set; }

    [InverseProperty("fk_id_ano_escolarNavigation")]
    public virtual ICollection<tb_historial_academico> tb_historial_academico { get; set; } = new List<tb_historial_academico>();

    [InverseProperty("fk_id_ano_escolarNavigation")]
    public virtual ICollection<tb_transiciones_estudiantes> tb_transiciones_estudiantes { get; set; } = new List<tb_transiciones_estudiantes>();
}