// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_boletas", Schema = "mcol")]
public partial class tb_boletas
{
    [Key]
    public int id_boleta { get; set; }

    public int? fk_id_estudiante { get; set; }

    [StringLength(20)]
    public string periodo { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? promedio { get; set; }

    [Column(TypeName = "text")]
    public string observaciones { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_boletas")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }
}