// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_ciudades", Schema = "mcol")]
public partial class tb_ciudades
{
    [Key]
    public int id_ciudad { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    public int? fk_id_departamento { get; set; }

    [ForeignKey("fk_id_departamento")]
    [InverseProperty("tb_ciudades")]
    public virtual tb_departamentos fk_id_departamentoNavigation { get; set; }
}