// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_carnets", Schema = "mcol")]
public partial class tb_carnets
{
    [Key]
    public int id_carnet { get; set; }

    public int? fk_id_estudiante { get; set; }

    [StringLength(50)]
    public string tipo { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_emision { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_carnets")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }

    [InverseProperty("fk_id_carnetNavigation")]
    public virtual ICollection<tb_control_acceso> tb_control_acceso { get; set; } = new List<tb_control_acceso>();
}