// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_configuracion_mensajeria", Schema = "mcol")]
public partial class tb_configuracion_mensajeria
{
    [Key]
    public int id_configuracion { get; set; }

    [StringLength(100)]
    public string smtp_servidor { get; set; }

    public int? smtp_puerto { get; set; }

    [StringLength(100)]
    public string smtp_usuario { get; set; }

    [StringLength(100)]
    public string smtp_password { get; set; }
}