// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_calificaciones", Schema = "mcol")]
public partial class tb_calificaciones
{
    [Key]
    public int id_calificacion { get; set; }

    public int? fk_id_estudiante { get; set; }

    public int? fk_id_evaluacion { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? nota { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_calificaciones")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }

    [ForeignKey("fk_id_evaluacion")]
    [InverseProperty("tb_calificaciones")]
    public virtual tb_evaluaciones fk_id_evaluacionNavigation { get; set; }
}