// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_contratos", Schema = "mcol")]
public partial class tb_contratos
{
    [Key]
    public int id_contrato { get; set; }

    public int? fk_id_empleado { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_inicio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_fin { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? salario { get; set; }

    [ForeignKey("fk_id_empleado")]
    [InverseProperty("tb_contratos")]
    public virtual tb_empleados fk_id_empleadoNavigation { get; set; }
}