// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_comunicaciones_institucionales", Schema = "mcol")]
public partial class tb_comunicaciones_institucionales
{
    [Key]
    public int id_comunicacion { get; set; }

    public int? fk_id_colegio { get; set; }

    [Column(TypeName = "text")]
    public string mensaje { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_envio { get; set; }

    [ForeignKey("fk_id_colegio")]
    [InverseProperty("tb_comunicaciones_institucionales")]
    public virtual tb_colegios fk_id_colegioNavigation { get; set; }
}