// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_control_acceso", Schema = "mcol")]
public partial class tb_control_acceso
{
    [Key]
    public int id_control { get; set; }

    public int? fk_id_carnet { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_acceso { get; set; }

    [StringLength(50)]
    public string tipo_acceso { get; set; }

    [ForeignKey("fk_id_carnet")]
    [InverseProperty("tb_control_acceso")]
    public virtual tb_carnets fk_id_carnetNavigation { get; set; }
}