// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_certificados", Schema = "mcol")]
public partial class tb_certificados
{
    [Key]
    public int id_certificado { get; set; }

    public int? fk_id_estudiante { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_certificados")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }
}