// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_comunicaciones", Schema = "mcol")]
public partial class tb_comunicaciones
{
    [Key]
    public int id_comunicacion { get; set; }

    public int? fk_id_usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha { get; set; }

    [StringLength(50)]
    public string tipo { get; set; }

    [Column(TypeName = "text")]
    public string mensaje { get; set; }

    [ForeignKey("fk_id_usuario")]
    [InverseProperty("tb_comunicaciones")]
    public virtual tb_usuarios fk_id_usuarioNavigation { get; set; }
}