// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_departamentos", Schema = "mcol")]
public partial class tb_departamentos
{
    [Key]
    public int id_departamento { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    public int? fk_id_pais { get; set; }

    [ForeignKey("fk_id_pais")]
    [InverseProperty("tb_departamentos")]
    public virtual tb_paises fk_id_paisNavigation { get; set; }

    [InverseProperty("fk_id_departamentoNavigation")]
    public virtual ICollection<tb_ciudades> tb_ciudades { get; set; } = new List<tb_ciudades>();
}