// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_encuestas_satisfaccion", Schema = "mcol")]
public partial class tb_encuestas_satisfaccion
{
    [Key]
    public int id_encuesta { get; set; }

    [StringLength(100)]
    public string titulo { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [InverseProperty("fk_id_encuestaNavigation")]
    public virtual ICollection<tb_preguntas_encuesta> tb_preguntas_encuesta { get; set; } = new List<tb_preguntas_encuesta>();
}