// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_estudiantes", Schema = "mcol")]
public partial class tb_estudiantes
{
    [Key]
    public int id_estudiante { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }

    [StringLength(50)]
    public string apellido { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_nacimiento { get; set; }

    public int? fk_id_grado { get; set; }

    [ForeignKey("fk_id_grado")]
    [InverseProperty("tb_estudiantes")]
    public virtual tb_grados fk_id_gradoNavigation { get; set; }

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_boletas> tb_boletas { get; set; } = new List<tb_boletas>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_calificaciones> tb_calificaciones { get; set; } = new List<tb_calificaciones>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_carnets> tb_carnets { get; set; } = new List<tb_carnets>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_certificados> tb_certificados { get; set; } = new List<tb_certificados>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_consulta_asistencia> tb_consulta_asistencia { get; set; } = new List<tb_consulta_asistencia>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_consulta_notas> tb_consulta_notas { get; set; } = new List<tb_consulta_notas>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_consulta_pagos> tb_consulta_pagos { get; set; } = new List<tb_consulta_pagos>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_historial_academico> tb_historial_academico { get; set; } = new List<tb_historial_academico>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_incidencias> tb_incidencias { get; set; } = new List<tb_incidencias>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_inscripciones> tb_inscripciones { get; set; } = new List<tb_inscripciones>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_pagos> tb_pagos { get; set; } = new List<tb_pagos>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_participacion_actividades> tb_participacion_actividades { get; set; } = new List<tb_participacion_actividades>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_reportes> tb_reportes { get; set; } = new List<tb_reportes>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_reportes_asistencia> tb_reportes_asistencia { get; set; } = new List<tb_reportes_asistencia>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_reportes_financieros> tb_reportes_financieros { get; set; } = new List<tb_reportes_financieros>();

    [InverseProperty("fk_id_estudianteNavigation")]
    public virtual ICollection<tb_transiciones_estudiantes> tb_transiciones_estudiantes { get; set; } = new List<tb_transiciones_estudiantes>();
}