// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_evaluaciones", Schema = "mcol")]
public partial class tb_evaluaciones
{
    [Key]
    public int id_evaluacion { get; set; }

    public int? fk_id_curso { get; set; }

    [StringLength(50)]
    public string tipo_evaluacion { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [ForeignKey("fk_id_curso")]
    [InverseProperty("tb_evaluaciones")]
    public virtual tb_asignacion_cursos fk_id_cursoNavigation { get; set; }

    [InverseProperty("fk_id_evaluacionNavigation")]
    public virtual ICollection<tb_calificaciones> tb_calificaciones { get; set; } = new List<tb_calificaciones>();
}