// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_empleados", Schema = "mcol")]
public partial class tb_empleados
{
    [Key]
    public int id_empleado { get; set; }

    [StringLength(50)]
    public string nombre { get; set; }

    [StringLength(50)]
    public string apellido { get; set; }

    [StringLength(50)]
    public string cargo { get; set; }

    [InverseProperty("fk_id_docenteNavigation")]
    public virtual ICollection<tb_asignacion_cursos> tb_asignacion_cursos { get; set; } = new List<tb_asignacion_cursos>();

    [InverseProperty("fk_id_empleadoNavigation")]
    public virtual ICollection<tb_contratos> tb_contratos { get; set; } = new List<tb_contratos>();

    [InverseProperty("fk_id_empleadoNavigation")]
    public virtual ICollection<tb_nominas> tb_nominas { get; set; } = new List<tb_nominas>();
}