// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_facturas", Schema = "mcol")]
public partial class tb_facturas
{
    [Key]
    public int id_factura { get; set; }

    public int? fk_id_pago { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? total { get; set; }

    [StringLength(50)]
    public string estado { get; set; }

    [ForeignKey("fk_id_pago")]
    [InverseProperty("tb_facturas")]
    public virtual tb_pagos fk_id_pagoNavigation { get; set; }
}