// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_grados", Schema = "mcol")]
public partial class tb_grados
{
    [Key]
    public int id_grado { get; set; }

    [StringLength(50)]
    public string descripcion { get; set; }

    [InverseProperty("fk_id_gradoNavigation")]
    public virtual ICollection<tb_estudiantes> tb_estudiantes { get; set; } = new List<tb_estudiantes>();

    [InverseProperty("fk_id_gradoNavigation")]
    public virtual ICollection<tb_historial_academico> tb_historial_academico { get; set; } = new List<tb_historial_academico>();

    [InverseProperty("fk_id_gradoNavigation")]
    public virtual ICollection<tb_inscripciones> tb_inscripciones { get; set; } = new List<tb_inscripciones>();

    [InverseProperty("fk_id_grado_actualNavigation")]
    public virtual ICollection<tb_transiciones_estudiantes> tb_transiciones_estudiantesfk_id_grado_actualNavigation { get; set; } = new List<tb_transiciones_estudiantes>();

    [InverseProperty("fk_id_grado_siguienteNavigation")]
    public virtual ICollection<tb_transiciones_estudiantes> tb_transiciones_estudiantesfk_id_grado_siguienteNavigation { get; set; } = new List<tb_transiciones_estudiantes>();
}