// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_inscripciones", Schema = "mcol")]
public partial class tb_inscripciones
{
    [Key]
    public int id_inscripcion { get; set; }

    public int? fk_id_estudiante { get; set; }

    public int? fk_id_grado { get; set; }

    public int? fk_id_colegio { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_inscripcion { get; set; }

    [ForeignKey("fk_id_colegio")]
    [InverseProperty("tb_inscripciones")]
    public virtual tb_colegios fk_id_colegioNavigation { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_inscripciones")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }

    [ForeignKey("fk_id_grado")]
    [InverseProperty("tb_inscripciones")]
    public virtual tb_grados fk_id_gradoNavigation { get; set; }
}