// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_informes_auditoria", Schema = "mcol")]
public partial class tb_informes_auditoria
{
    [Key]
    public int id_informe { get; set; }

    public int? fk_id_auditoria { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [ForeignKey("fk_id_auditoria")]
    [InverseProperty("tb_informes_auditoria")]
    public virtual tb_auditorias fk_id_auditoriaNavigation { get; set; }
}