// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_incidencias", Schema = "mcol")]
public partial class tb_incidencias
{
    [Key]
    public int id_incidencia { get; set; }

    public int? fk_id_estudiante { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_incidencias")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }

    [InverseProperty("fk_id_incidenciaNavigation")]
    public virtual ICollection<tb_planes_accion> tb_planes_accion { get; set; } = new List<tb_planes_accion>();
}