// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_mantenimiento", Schema = "mcol")]
public partial class tb_mantenimiento
{
    [Key]
    public int id_mantenimiento { get; set; }

    public int? fk_id_aula { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [ForeignKey("fk_id_aula")]
    [InverseProperty("tb_mantenimiento")]
    public virtual tb_aulas fk_id_aulaNavigation { get; set; }
}