// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_modulos", Schema = "mcol")]
public partial class tb_modulos
{
    [Key]
    public int id_modulo { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }
}