// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_modulos", Schema = "mcol")]
public partial class tb_modulos
{
    [Key]
    public int id_modulo { get; set; }

    [Required]
    [StringLength(150)]
    public string descripcion { get; set; }

    [Required]
    [StringLength(150)]
    public string icono { get; set; }

    public bool estado { get; set; }

    public int orden { get; set; }

    [InverseProperty("fk_id_moduloNavigation")]
    public virtual ICollection<tb_paginas> tb_paginas { get; set; } = new List<tb_paginas>();
}