// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_nominas", Schema = "mcol")]
public partial class tb_nominas
{
    [Key]
    public int id_nomina { get; set; }

    public int? fk_id_empleado { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? monto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_pago { get; set; }

    [ForeignKey("fk_id_empleado")]
    [InverseProperty("tb_nominas")]
    public virtual tb_empleados fk_id_empleadoNavigation { get; set; }
}