// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_oficinas_perfiles", Schema = "mcol")]
public partial class tb_oficinas_perfiles
{
    [Key]
    public int id_oficina_perfil { get; set; }

    public int? id_oficina { get; set; }

    public int? fk_id_perfil { get; set; }

    [ForeignKey("fk_id_perfil")]
    [InverseProperty("tb_oficinas_perfiles")]
    public virtual tb_perfiles fk_id_perfilNavigation { get; set; }
}