// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_pagos", Schema = "mcol")]
public partial class tb_pagos
{
    [Key]
    public int id_pago { get; set; }

    public int? fk_id_estudiante { get; set; }

    [Column(TypeName = "decimal(10, 2)")]
    public decimal? monto { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_pago { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_pagos")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }

    [InverseProperty("fk_id_pagoNavigation")]
    public virtual ICollection<tb_facturas> tb_facturas { get; set; } = new List<tb_facturas>();
}