// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_paginas", Schema = "mcol")]
public partial class tb_paginas
{
    [Key]
    public int id_pagina { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [StringLength(255)]
    public string url { get; set; }

    [InverseProperty("fk_id_paginaNavigation")]
    public virtual ICollection<tb_permisos> tb_permisos { get; set; } = new List<tb_permisos>();

    [InverseProperty("fk_id_paginaNavigation")]
    public virtual ICollection<tb_prioridad_paginas> tb_prioridad_paginas { get; set; } = new List<tb_prioridad_paginas>();
}