// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_permisos", Schema = "mcol")]
public partial class tb_permisos
{
    [Key]
    public int id_permiso { get; set; }

    public int? fk_id_pagina { get; set; }

    public int fk_id_perfil { get; set; }

    public bool lectura { get; set; }

    public bool crear { get; set; }

    public bool actualizar { get; set; }

    public bool borrar { get; set; }

    public bool anular { get; set; }

    public bool anular_dia { get; set; }

    [StringLength(255)]
    public string usuario_creacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_creacion { get; set; }

    [StringLength(255)]
    public string usuario_actualizacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_actualizacion { get; set; }

    [StringLength(128)]
    [Unicode(false)]
    public string app_name_origen { get; set; }

    [ForeignKey("fk_id_pagina")]
    [InverseProperty("tb_permisos")]
    public virtual tb_paginas fk_id_paginaNavigation { get; set; }

    [ForeignKey("fk_id_perfil")]
    [InverseProperty("tb_permisos")]
    public virtual tb_perfiles fk_id_perfilNavigation { get; set; }
}