// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_paginas", Schema = "mcol")]
[Index("id_pagina", Name = "UQ_tb_paginas_id_pagina", IsUnique = true)]
public partial class tb_paginas
{
    [Key]
    public int id_pagina { get; set; }

    public int fk_id_modulo { get; set; }

    [Required]
    [StringLength(100)]
    public string descripcion { get; set; }

    [StringLength(50)]
    public string icono { get; set; }

    [Required]
    public string ruta { get; set; }

    public bool estado { get; set; }

    [StringLength(50)]
    public string reporte { get; set; }

    public int? orden { get; set; }

    [StringLength(50)]
    public string nombre_title_html { get; set; }

    [ForeignKey("fk_id_modulo")]
    [InverseProperty("tb_paginas")]
    public virtual tb_modulos fk_id_moduloNavigation { get; set; }

    [InverseProperty("fk_id_paginaNavigation")]
    public virtual ICollection<tb_permisos> tb_permisos { get; set; } = new List<tb_permisos>();

    [InverseProperty("fk_id_paginaNavigation")]
    public virtual ICollection<tb_prioridad_paginas> tb_prioridad_paginas { get; set; } = new List<tb_prioridad_paginas>();
}