// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_participacion_actividades", Schema = "mcol")]
public partial class tb_participacion_actividades
{
    [Key]
    public int id_participacion { get; set; }

    public int? fk_id_actividad { get; set; }

    public int? fk_id_estudiante { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha_participacion { get; set; }

    [ForeignKey("fk_id_actividad")]
    [InverseProperty("tb_participacion_actividades")]
    public virtual tb_actividades_extracurriculares fk_id_actividadNavigation { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_participacion_actividades")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }
}