// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_prioridad_paginas", Schema = "mcol")]
public partial class tb_prioridad_paginas
{
    [Key]
    public int id_prioridad { get; set; }

    public int? fk_id_pagina { get; set; }

    public int? prioridad { get; set; }

    [ForeignKey("fk_id_pagina")]
    [InverseProperty("tb_prioridad_paginas")]
    public virtual tb_paginas fk_id_paginaNavigation { get; set; }
}