// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_pagina_institucional", Schema = "mcol")]
public partial class tb_pagina_institucional
{
    [Key]
    public int id_pagina { get; set; }

    [StringLength(100)]
    public string titulo { get; set; }

    [Column(TypeName = "text")]
    public string contenido { get; set; }
}