// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_perfiles", Schema = "mcol")]
public partial class tb_perfiles
{
    [Key]
    public int id_perfil { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [Column(TypeName = "text")]
    public string descripcion { get; set; }

    [InverseProperty("fk_id_perfilNavigation")]
    public virtual ICollection<tb_oficinas_perfiles> tb_oficinas_perfiles { get; set; } = new List<tb_oficinas_perfiles>();

    [InverseProperty("fk_id_perfilNavigation")]
    public virtual ICollection<tb_permisos> tb_permisos { get; set; } = new List<tb_permisos>();

    [InverseProperty("fk_id_perfilNavigation")]
    public virtual ICollection<tb_usuarios_perfiles> tb_usuarios_perfiles { get; set; } = new List<tb_usuarios_perfiles>();
}