// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_parametros", Schema = "mcol")]
public partial class tb_parametros
{
    [Key]
    public int id_parametro { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [StringLength(255)]
    public string valor { get; set; }
}