// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_perfiles", Schema = "mcol")]
public partial class tb_perfiles
{
    [Key]
    public int id_perfil { get; set; }

    [Required]
    [StringLength(200)]
    public string descripcion { get; set; }

    public bool estado { get; set; }

    public long? id_origen { get; set; }

    [StringLength(255)]
    public string usuario_creacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_creacion { get; set; }

    [StringLength(255)]
    public string usuario_modificacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_modificacion { get; set; }

    [InverseProperty("fk_id_perfilNavigation")]
    public virtual ICollection<tb_permisos> tb_permisos { get; set; } = new List<tb_permisos>();

    [InverseProperty("fk_id_perfilNavigation")]
    public virtual ICollection<tb_usuarios_perfiles> tb_usuarios_perfiles { get; set; } = new List<tb_usuarios_perfiles>();
}