// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_paises", Schema = "mcol")]
public partial class tb_paises
{
    [Key]
    public int id_pais { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [InverseProperty("fk_id_paisNavigation")]
    public virtual ICollection<tb_departamentos> tb_departamentos { get; set; } = new List<tb_departamentos>();
}