// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_reportes_asistencia", Schema = "mcol")]
public partial class tb_reportes_asistencia
{
    [Key]
    public int id_reporte_asistencia { get; set; }

    public int? fk_id_estudiante { get; set; }

    [Column(TypeName = "date")]
    public DateTime? fecha { get; set; }

    [StringLength(20)]
    public string estado_asistencia { get; set; }

    [ForeignKey("fk_id_estudiante")]
    [InverseProperty("tb_reportes_asistencia")]
    public virtual tb_estudiantes fk_id_estudianteNavigation { get; set; }
}