// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_respuestas_encuesta", Schema = "mcol")]
public partial class tb_respuestas_encuesta
{
    [Key]
    public int id_respuesta { get; set; }

    public int? fk_id_pregunta { get; set; }

    [Column(TypeName = "text")]
    public string respuesta { get; set; }

    [ForeignKey("fk_id_pregunta")]
    [InverseProperty("tb_respuestas_encuesta")]
    public virtual tb_preguntas_encuesta fk_id_preguntaNavigation { get; set; }
}