// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_rutas_documentos", Schema = "mcol")]
public partial class tb_rutas_documentos
{
    [Key]
    public int id_ruta { get; set; }

    [StringLength(255)]
    public string ruta { get; set; }
}