// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_tipos_identificacion", Schema = "mcol")]
public partial class tb_tipos_identificacion
{
    [Key]
    public int id_tipo_identificacion { get; set; }

    [StringLength(100)]
    public string descripcion { get; set; }
}