// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_tipos_parentesco", Schema = "mcol")]
public partial class tb_tipos_parentesco
{
    [Key]
    public int id_parentesco { get; set; }

    [StringLength(50)]
    public string descripcion { get; set; }
}