// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_usuarios_logueados", Schema = "mcol")]
public partial class tb_usuarios_logueados
{
    [Key]
    public int id_logueado { get; set; }

    public int? fk_id_usuario { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_logueo { get; set; }

    [ForeignKey("fk_id_usuario")]
    [InverseProperty("tb_usuarios_logueados")]
    public virtual tb_usuarios fk_id_usuarioNavigation { get; set; }
}