// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_usuarios", Schema = "mcol")]
public partial class tb_usuarios
{
    [Key]
    public int id_usuario { get; set; }

    [StringLength(100)]
    public string nombre { get; set; }

    [StringLength(100)]
    public string password { get; set; }

    [StringLength(100)]
    public string email { get; set; }

    [InverseProperty("fk_id_usuarioNavigation")]
    public virtual ICollection<tb_comunicaciones> tb_comunicaciones { get; set; } = new List<tb_comunicaciones>();

    [InverseProperty("fk_id_usuarioNavigation")]
    public virtual ICollection<tb_usuarios_logueados> tb_usuarios_logueados { get; set; } = new List<tb_usuarios_logueados>();

    [InverseProperty("fk_id_usuarioNavigation")]
    public virtual ICollection<tb_usuarios_perfiles> tb_usuarios_perfiles { get; set; } = new List<tb_usuarios_perfiles>();
}