// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_usuarios_logueados", Schema = "mcol")]
public partial class tb_usuarios_logueados
{
    [Key]
    public long id_usuarioslogueados { get; set; }

    [StringLength(255)]
    public string login { get; set; }

    public string key_sesion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? fecha_conexion { get; set; }

    [StringLength(50)]
    public string ip_conexion { get; set; }
}