// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace MCol.DAL.Modelo;

[Table("tb_usuarios_perfiles", Schema = "mcol")]
public partial class tb_usuarios_perfiles
{
    [Key]
    public int id_usuario_perfil { get; set; }

    public int? fk_id_usuario { get; set; }

    public int? fk_id_perfil { get; set; }

    [ForeignKey("fk_id_perfil")]
    [InverseProperty("tb_usuarios_perfiles")]
    public virtual tb_perfiles fk_id_perfilNavigation { get; set; }

    [ForeignKey("fk_id_usuario")]
    [InverseProperty("tb_usuarios_perfiles")]
    public virtual tb_usuarios fk_id_usuarioNavigation { get; set; }
}